# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(942, 377)
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(80, 120, 71, 31))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setGeometry(QtCore.QRect(320, 50, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(dialog)
        self.label_6.setGeometry(QtCore.QRect(660, 20, 72, 15))
        self.label_6.setObjectName("label_6")
        self.takeImage = QtWidgets.QPushButton(dialog)
        self.takeImage.setGeometry(QtCore.QRect(830, 70, 93, 28))
        self.takeImage.setObjectName("takeImage")
        self.lowRedV = QtWidgets.QSpinBox(dialog)
        self.lowRedV.setGeometry(QtCore.QRect(460, 70, 81, 31))
        self.lowRedV.setMaximum(255)
        self.lowRedV.setObjectName("lowRedV")
        self.frontCameraID = QtWidgets.QSpinBox(dialog)
        self.frontCameraID.setGeometry(QtCore.QRect(450, 220, 81, 31))
        self.frontCameraID.setMaximum(3)
        self.frontCameraID.setObjectName("frontCameraID")
        self.label_7 = QtWidgets.QLabel(dialog)
        self.label_7.setGeometry(QtCore.QRect(360, 230, 72, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(dialog)
        self.label_8.setGeometry(QtCore.QRect(360, 270, 72, 21))
        self.label_8.setObjectName("label_8")
        self.bottomCameraID = QtWidgets.QSpinBox(dialog)
        self.bottomCameraID.setGeometry(QtCore.QRect(450, 270, 81, 31))
        self.bottomCameraID.setMaximum(3)
        self.bottomCameraID.setObjectName("bottomCameraID")
        self.frontCameraOpen = QtWidgets.QPushButton(dialog)
        self.frontCameraOpen.setGeometry(QtCore.QRect(570, 220, 111, 31))
        self.frontCameraOpen.setObjectName("frontCameraOpen")
        self.bottomCameraOpen = QtWidgets.QPushButton(dialog)
        self.bottomCameraOpen.setGeometry(QtCore.QRect(570, 270, 111, 31))
        self.bottomCameraOpen.setObjectName("bottomCameraOpen")
        self.outputData = QtWidgets.QPushButton(dialog)
        self.outputData.setGeometry(QtCore.QRect(390, 320, 93, 28))
        self.outputData.setObjectName("outputData")
        self.shutDown = QtWidgets.QPushButton(dialog)
        self.shutDown.setGeometry(QtCore.QRect(530, 320, 93, 28))
        self.shutDown.setObjectName("shutDown")
        self.threshold = QtWidgets.QPushButton(dialog)
        self.threshold.setGeometry(QtCore.QRect(830, 150, 93, 28))
        self.threshold.setObjectName("threshold")
        self.lowRedH = QtWidgets.QSpinBox(dialog)
        self.lowRedH.setGeometry(QtCore.QRect(300, 70, 81, 31))
        self.lowRedH.setMaximum(255)
        self.lowRedH.setObjectName("lowRedH")
        self.lowRedS = QtWidgets.QSpinBox(dialog)
        self.lowRedS.setGeometry(QtCore.QRect(380, 70, 81, 31))
        self.lowRedS.setMaximum(255)
        self.lowRedS.setObjectName("lowRedS")
        self.lowGreenS = QtWidgets.QSpinBox(dialog)
        self.lowGreenS.setGeometry(QtCore.QRect(380, 110, 81, 31))
        self.lowGreenS.setMaximum(255)
        self.lowGreenS.setObjectName("lowGreenS")
        self.lowGreenV = QtWidgets.QSpinBox(dialog)
        self.lowGreenV.setGeometry(QtCore.QRect(460, 110, 81, 31))
        self.lowGreenV.setMaximum(255)
        self.lowGreenV.setObjectName("lowGreenV")
        self.lowGreenH = QtWidgets.QSpinBox(dialog)
        self.lowGreenH.setGeometry(QtCore.QRect(300, 110, 81, 31))
        self.lowGreenH.setMaximum(255)
        self.lowGreenH.setObjectName("lowGreenH")
        self.lowBlackS = QtWidgets.QSpinBox(dialog)
        self.lowBlackS.setGeometry(QtCore.QRect(380, 150, 81, 31))
        self.lowBlackS.setMaximum(255)
        self.lowBlackS.setObjectName("lowBlackS")
        self.lowBlackV = QtWidgets.QSpinBox(dialog)
        self.lowBlackV.setGeometry(QtCore.QRect(460, 150, 81, 31))
        self.lowBlackV.setMaximum(255)
        self.lowBlackV.setObjectName("lowBlackV")
        self.lowBlackH = QtWidgets.QSpinBox(dialog)
        self.lowBlackH.setGeometry(QtCore.QRect(300, 150, 81, 31))
        self.lowBlackH.setMaximum(255)
        self.lowBlackH.setObjectName("lowBlackH")
        self.highRedS = QtWidgets.QSpinBox(dialog)
        self.highRedS.setGeometry(QtCore.QRect(640, 70, 81, 31))
        self.highRedS.setMaximum(255)
        self.highRedS.setObjectName("highRedS")
        self.highRedV = QtWidgets.QSpinBox(dialog)
        self.highRedV.setGeometry(QtCore.QRect(720, 70, 81, 31))
        self.highRedV.setMaximum(255)
        self.highRedV.setObjectName("highRedV")
        self.highRedH = QtWidgets.QSpinBox(dialog)
        self.highRedH.setGeometry(QtCore.QRect(560, 70, 81, 31))
        self.highRedH.setMaximum(255)
        self.highRedH.setObjectName("highRedH")
        self.highGreenS = QtWidgets.QSpinBox(dialog)
        self.highGreenS.setGeometry(QtCore.QRect(640, 110, 81, 31))
        self.highGreenS.setMaximum(255)
        self.highGreenS.setObjectName("highGreenS")
        self.highGreenV = QtWidgets.QSpinBox(dialog)
        self.highGreenV.setGeometry(QtCore.QRect(720, 110, 81, 31))
        self.highGreenV.setMaximum(255)
        self.highGreenV.setObjectName("highGreenV")
        self.highGreenH = QtWidgets.QSpinBox(dialog)
        self.highGreenH.setGeometry(QtCore.QRect(560, 110, 81, 31))
        self.highGreenH.setMaximum(255)
        self.highGreenH.setObjectName("highGreenH")
        self.highBlackS = QtWidgets.QSpinBox(dialog)
        self.highBlackS.setGeometry(QtCore.QRect(640, 150, 81, 31))
        self.highBlackS.setMaximum(255)
        self.highBlackS.setObjectName("highBlackS")
        self.highBlackV = QtWidgets.QSpinBox(dialog)
        self.highBlackV.setGeometry(QtCore.QRect(720, 150, 81, 31))
        self.highBlackV.setMaximum(255)
        self.highBlackV.setObjectName("highBlackV")
        self.highBlackH = QtWidgets.QSpinBox(dialog)
        self.highBlackH.setGeometry(QtCore.QRect(560, 150, 81, 31))
        self.highBlackH.setMaximum(255)
        self.highBlackH.setObjectName("highBlackH")
        self.label_9 = QtWidgets.QLabel(dialog)
        self.label_9.setGeometry(QtCore.QRect(400, 50, 21, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(dialog)
        self.label_10.setGeometry(QtCore.QRect(480, 50, 21, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(dialog)
        self.label_11.setGeometry(QtCore.QRect(660, 50, 21, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(dialog)
        self.label_12.setGeometry(QtCore.QRect(740, 50, 21, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(dialog)
        self.label_13.setGeometry(QtCore.QRect(580, 50, 21, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(dialog)
        self.label_14.setGeometry(QtCore.QRect(400, 20, 72, 15))
        self.label_14.setObjectName("label_14")
        self.debugMode = QtWidgets.QCheckBox(dialog)
        self.debugMode.setEnabled(True)
        self.debugMode.setGeometry(QtCore.QRect(190, 230, 91, 19))
        self.debugMode.setObjectName("debugMode")
        self.transferMode = QtWidgets.QCheckBox(dialog)
        self.transferMode.setGeometry(QtCore.QRect(190, 270, 91, 19))
        self.transferMode.setObjectName("transferMode")
        self.testCamID = QtWidgets.QSpinBox(dialog)
        self.testCamID.setGeometry(QtCore.QRect(90, 80, 81, 31))
        self.testCamID.setMaximum(3)
        self.testCamID.setObjectName("testCamID")
        self.label_15 = QtWidgets.QLabel(dialog)
        self.label_15.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.label_15.setObjectName("label_15")
        self.pickImage = QtWidgets.QPushButton(dialog)
        self.pickImage.setGeometry(QtCore.QRect(830, 110, 93, 28))
        self.pickImage.setObjectName("pickImage")
        self.redRadio = QtWidgets.QRadioButton(dialog)
        self.redRadio.setGeometry(QtCore.QRect(220, 80, 71, 19))
        self.redRadio.setObjectName("redRadio")
        self.greenRadio = QtWidgets.QRadioButton(dialog)
        self.greenRadio.setGeometry(QtCore.QRect(220, 120, 61, 16))
        self.greenRadio.setObjectName("greenRadio")
        self.blackRadio = QtWidgets.QRadioButton(dialog)
        self.blackRadio.setGeometry(QtCore.QRect(220, 150, 61, 21))
        self.blackRadio.setObjectName("blackRadio")
        self.frontCameraShut = QtWidgets.QPushButton(dialog)
        self.frontCameraShut.setGeometry(QtCore.QRect(700, 220, 111, 31))
        self.frontCameraShut.setObjectName("frontCameraShut")
        self.bottomCameraShut = QtWidgets.QPushButton(dialog)
        self.bottomCameraShut.setGeometry(QtCore.QRect(700, 270, 111, 31))
        self.bottomCameraShut.setObjectName("bottomCameraShut")
        self.grayMode = QtWidgets.QCheckBox(dialog)
        self.grayMode.setEnabled(True)
        self.grayMode.setGeometry(QtCore.QRect(840, 280, 91, 19))
        self.grayMode.setObjectName("grayMode")

        self.retranslateUi(dialog)
        self.frontCameraOpen.clicked.connect(dialog.pressCam1)
        self.bottomCameraOpen.clicked.connect(dialog.pressCam2)
        self.takeImage.clicked.connect(dialog.pressCutButton)
        self.threshold.clicked.connect(dialog.pressCmpButton)
        self.outputData.clicked.connect(dialog.pressLog)
        self.shutDown.clicked.connect(dialog.pressShut)
        self.pickImage.clicked.connect(dialog.pressGetImage)
        self.lowRedH.valueChanged['int'].connect(dialog.pressCmpButton)
        self.lowRedS.valueChanged['int'].connect(dialog.pressCmpButton)
        self.lowRedV.valueChanged['int'].connect(dialog.pressCmpButton)
        self.highRedH.valueChanged['int'].connect(dialog.pressCmpButton)
        self.highRedS.valueChanged['int'].connect(dialog.pressCmpButton)
        self.highRedV.valueChanged['int'].connect(dialog.pressCmpButton)
        self.lowGreenH.valueChanged['int'].connect(dialog.pressCmpButton)
        self.lowGreenS.valueChanged['int'].connect(dialog.pressCmpButton)
        self.lowGreenV.valueChanged['int'].connect(dialog.pressCmpButton)
        self.highGreenH.valueChanged['int'].connect(dialog.pressCmpButton)
        self.highGreenS.valueChanged['int'].connect(dialog.pressCmpButton)
        self.highGreenV.valueChanged['int'].connect(self.threshold.click)
        self.highBlackV.valueChanged['int'].connect(self.threshold.click)
        self.highBlackS.valueChanged['int'].connect(self.threshold.click)
        self.highBlackH.valueChanged['int'].connect(self.threshold.click)
        self.lowBlackV.valueChanged['int'].connect(self.threshold.click)
        self.lowBlackS.valueChanged['int'].connect(self.threshold.click)
        self.lowBlackH.valueChanged['int'].connect(self.threshold.click)
        self.frontCameraShut.clicked.connect(dialog.shutCam1)
        self.bottomCameraShut.clicked.connect(dialog.shutCam2)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.label.setText(_translate("dialog", "参数设定"))
        self.label_5.setText(_translate("dialog", "H"))
        self.label_6.setText(_translate("dialog", "高"))
        self.takeImage.setText(_translate("dialog", "开启摄像"))
        self.label_7.setText(_translate("dialog", "前摄像头"))
        self.label_8.setText(_translate("dialog", "底摄像头"))
        self.frontCameraOpen.setText(_translate("dialog", "开启摄像头1"))
        self.bottomCameraOpen.setText(_translate("dialog", "开启摄像头2"))
        self.outputData.setText(_translate("dialog", "导出参数"))
        self.shutDown.setText(_translate("dialog", "关闭程序"))
        self.threshold.setText(_translate("dialog", "阈值对比"))
        self.label_9.setText(_translate("dialog", "S"))
        self.label_10.setText(_translate("dialog", "V"))
        self.label_11.setText(_translate("dialog", "S"))
        self.label_12.setText(_translate("dialog", "V"))
        self.label_13.setText(_translate("dialog", "H"))
        self.label_14.setText(_translate("dialog", "低"))
        self.debugMode.setText(_translate("dialog", "调试模式"))
        self.transferMode.setText(_translate("dialog", "传输模式"))
        self.label_15.setText(_translate("dialog", "测试摄像头"))
        self.pickImage.setText(_translate("dialog", "选定图片"))
        self.redRadio.setText(_translate("dialog", "红色"))
        self.greenRadio.setText(_translate("dialog", "绿色"))
        self.blackRadio.setText(_translate("dialog", "黑色"))
        self.frontCameraShut.setText(_translate("dialog", "关闭摄像头1"))
        self.bottomCameraShut.setText(_translate("dialog", "关闭摄像头2"))
        self.grayMode.setText(_translate("dialog", "灰度图"))

