# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'color.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_color(object):
    def setupUi(self, color):
        color.setObjectName("color")
        color.resize(614, 361)
        self.capButton = QtWidgets.QPushButton(color)
        self.capButton.setGeometry(QtCore.QRect(210, 40, 201, 61))
        self.capButton.setObjectName("capButton")
        self.label = QtWidgets.QLabel(color)
        self.label.setGeometry(QtCore.QRect(60, 150, 31, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(color)
        self.label_2.setGeometry(QtCore.QRect(60, 210, 31, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(color)
        self.label_3.setGeometry(QtCore.QRect(60, 260, 31, 31))
        self.label_3.setObjectName("label_3")
        self.smallHslider = QtWidgets.QSlider(color)
        self.smallHslider.setGeometry(QtCore.QRect(130, 150, 161, 22))
        self.smallHslider.setMaximum(255)
        self.smallHslider.setOrientation(QtCore.Qt.Horizontal)
        self.smallHslider.setObjectName("smallHslider")
        self.largeHslider = QtWidgets.QSlider(color)
        self.largeHslider.setGeometry(QtCore.QRect(130, 170, 160, 22))
        self.largeHslider.setMaximum(255)
        self.largeHslider.setOrientation(QtCore.Qt.Horizontal)
        self.largeHslider.setObjectName("largeHslider")
        self.smallSslider = QtWidgets.QSlider(color)
        self.smallSslider.setGeometry(QtCore.QRect(130, 200, 161, 22))
        self.smallSslider.setMaximum(255)
        self.smallSslider.setOrientation(QtCore.Qt.Horizontal)
        self.smallSslider.setObjectName("smallSslider")
        self.largeSslider_2 = QtWidgets.QSlider(color)
        self.largeSslider_2.setGeometry(QtCore.QRect(130, 220, 161, 22))
        self.largeSslider_2.setMaximum(255)
        self.largeSslider_2.setOrientation(QtCore.Qt.Horizontal)
        self.largeSslider_2.setObjectName("largeSslider_2")
        self.smallVslider = QtWidgets.QSlider(color)
        self.smallVslider.setGeometry(QtCore.QRect(130, 250, 161, 22))
        self.smallVslider.setMaximum(255)
        self.smallVslider.setOrientation(QtCore.Qt.Horizontal)
        self.smallVslider.setObjectName("smallVslider")
        self.largeVslider = QtWidgets.QSlider(color)
        self.largeVslider.setGeometry(QtCore.QRect(130, 270, 161, 22))
        self.largeVslider.setMaximum(255)
        self.largeVslider.setOrientation(QtCore.Qt.Horizontal)
        self.largeVslider.setObjectName("largeVslider")
        self.smallHtext = QtWidgets.QPlainTextEdit(color)
        self.smallHtext.setGeometry(QtCore.QRect(300, 150, 121, 31))
        self.smallHtext.setObjectName("smallHtext")
        self.largeHtext = QtWidgets.QPlainTextEdit(color)
        self.largeHtext.setGeometry(QtCore.QRect(440, 150, 121, 31))
        self.largeHtext.setObjectName("largeHtext")
        self.smallStext = QtWidgets.QPlainTextEdit(color)
        self.smallStext.setGeometry(QtCore.QRect(300, 200, 121, 31))
        self.smallStext.setObjectName("smallStext")
        self.largeStext = QtWidgets.QPlainTextEdit(color)
        self.largeStext.setGeometry(QtCore.QRect(440, 200, 121, 31))
        self.largeStext.setObjectName("largeStext")
        self.smallVtext = QtWidgets.QPlainTextEdit(color)
        self.smallVtext.setGeometry(QtCore.QRect(300, 250, 121, 31))
        self.smallVtext.setObjectName("smallVtext")
        self.largeVtext = QtWidgets.QPlainTextEdit(color)
        self.largeVtext.setGeometry(QtCore.QRect(440, 250, 121, 31))
        self.largeVtext.setObjectName("largeVtext")

        self.retranslateUi(color)
        self.smallHslider.actionTriggered['int'].connect(color.smallH)
        self.largeHslider.actionTriggered['int'].connect(color.largeH)
        self.smallSslider.actionTriggered['int'].connect(color.smallS)
        self.largeSslider_2.actionTriggered['int'].connect(color.lrageS)
        self.smallVslider.actionTriggered['int'].connect(color.smallV)
        self.largeVslider.valueChanged['int'].connect(color.largeV)
        self.capButton.clicked.connect(color.capture)
        QtCore.QMetaObject.connectSlotsByName(color)

    def retranslateUi(self, color):
        _translate = QtCore.QCoreApplication.translate
        color.setWindowTitle(_translate("color", "Form"))
        self.capButton.setText(_translate("color", "捕获"))
        self.label.setText(_translate("color", "H"))
        self.label_2.setText(_translate("color", "S"))
        self.label_3.setText(_translate("color", "V"))

